name: tool_base_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tool_base:
    git: https://github.com/adrienbaron/tool_base
  #  tool_base:
  #    path: ../tool_base
  reporting:
    git: https://github.com/ventskus-roman/reporting

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.16.5
  mockito: ^4.1.4
